FROM tiangolo/uwsgi-nginx-flask:python3.12
RUN apt update -y && apt install ca-certificates --yes
RUN pip3 install psycopg2

COPY requirements.txt /app
RUN pip3 install -r requirements.txt

COPY pyproject.toml /app
COPY create_mock.py /app
COPY alembic.ini /app
COPY uwsgi-me.sh /app
COPY /migrations /app/migrations
COPY src /app/src
WORKDIR /app
RUN pip3 install .
EXPOSE 5000
CMD ./uwsgi-me.sh
