FROM tiangolo/uwsgi-nginx-flask:python3.7
RUN apt update && apt install ca-certificates --yes
RUN pip3 install psycopg2
COPY setup.py /app
COPY create_mock.py /app
COPY alembic.ini /app
COPY uwsgi-me.sh /app
COPY /migrations /app/migrations
COPY /cebulany /app/cebulany
WORKDIR /app
RUN python setup.py install
EXPOSE 5000
CMD ./uwsgi-me.sh
