"""empty message

Revision ID: 00259fb56e4b
Revises: f46a8f149209
Create Date: 2025-07-10 20:10:37.946946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00259fb56e4b'
down_revision = 'f46a8f149209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('innertransfer', 'from_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('innertransfer', 'to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('innertransfer', 'to_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('innertransfer', 'from_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
