"""add token time

Revision ID: 2625f2bf32bf
Revises: c19852e4dcda
Create Date: 2020-08-09 20:32:02.324936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2625f2bf32bf'
down_revision = 'c19852e4dcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_time')
        batch_op.drop_column('token')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
