"""empty message

Revision ID: 2a73402b0887
Revises: 00259fb56e4b
Create Date: 2025-10-20 18:50:50.960796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a73402b0887'
down_revision = '00259fb56e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('innerbudget', sa.Column('description_on_negative', sa.String(length=300), server_default='', nullable=False))
    op.add_column('innerbudget', sa.Column('description_on_positive', sa.String(length=300), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('innerbudget', 'description_on_positive')
    op.drop_column('innerbudget', 'description_on_negative')
    # ### end Alembic commands ###
