"""empty message

Revision ID: 415d32f993b8
Revises: 
Create Date: 2018-08-12 16:57:23.719990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415d32f993b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('line_num', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('main_line', sa.String(length=300), nullable=True),
    sa.Column('cost', sa.Numeric(precision=2), nullable=True),
    sa.Column('iban', sa.String(length=300), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('proposed_member_id', sa.Integer(), nullable=True),
    sa.Column('proposed_type_name', sa.String(length=300), nullable=True),
    sa.Column('proposed_type', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['proposed_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_line_num'), 'transaction', ['line_num'], unique=False)
    op.create_index(op.f('ix_transaction_name'), 'transaction', ['name'], unique=False)
    op.create_index(op.f('ix_transaction_ref_id'), 'transaction', ['ref_id'], unique=False)
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('cost', sa.Numeric(precision=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('cost', sa.Numeric(precision=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('cost', sa.Numeric(precision=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paidmonth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paidmonth')
    op.drop_table('other')
    op.drop_table('donation')
    op.drop_table('bill')
    op.drop_index(op.f('ix_transaction_ref_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_name'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_line_num'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
