"""empty message

Revision ID: 49afa9f7f649
Revises: 2414db0c7b89
Create Date: 2025-12-26 15:38:46.190085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49afa9f7f649'
down_revision = '2414db0c7b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('parent', sa.String(length=48), nullable=False))
    op.create_index(op.f('ix_document_parent'), 'document', ['parent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_parent'), table_name='document')
    op.drop_column('document', 'parent')
    # ### end Alembic commands ###
