"""remove old tables

Revision ID: 657669eb5fcb
Revises: c965332cc231
Create Date: 2018-08-26 19:08:29.642420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657669eb5fcb'
down_revision = 'c965332cc231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paidmonth')
    op.drop_table('other')
    op.drop_table('donation')
    op.drop_table('bill')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('proposed_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_type', sa.VARCHAR(length=300), nullable=True))

    op.create_table('bill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=2), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=2), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=2), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paidmonth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=2), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], [u'member.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
