"""empty message

Revision ID: 78b153fa548c
Revises: e8325b3bbc36
Create Date: 2025-03-16 20:20:52.915114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b153fa548c'
down_revision = 'e8325b3bbc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('description_on_positive', sa.String(length=300), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'description_on_positive')
    # ### end Alembic commands ###
