"""empty message

Revision ID: a4a8fb5dcc9a
Revises: e4180295fcc0
Create Date: 2025-11-05 17:44:41.285192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a8fb5dcc9a'
down_revision = 'e4180295fcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestion', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('suggestion', 'budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('suggestion', 'inner_budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suggestion', 'inner_budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('suggestion', 'budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('suggestion', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
