"""empty message

Revision ID: b297ba56988b
Revises: 89cfdd6128ca
Create Date: 2026-01-11 16:12:31.343223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b297ba56988b'
down_revision = '89cfdd6128ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('deleted_from_google', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'deleted_from_google')
    # ### end Alembic commands ###
