"""empty message

Revision ID: c56ac590fba7
Revises: a4a8fb5dcc9a
Create Date: 2025-12-26 15:02:45.640475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56ac590fba7'
down_revision = 'a4a8fb5dcc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_parent_id', sa.String(length=48), nullable=False),
    sa.Column('google_id', sa.String(length=48), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('accounting_record', sa.String(length=100), nullable=True),
    sa.Column('accounting_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_accounting_record'), 'document', ['accounting_record'], unique=False)
    op.create_index(op.f('ix_document_filename'), 'document', ['filename'], unique=False)
    op.create_index(op.f('ix_document_google_id'), 'document', ['google_id'], unique=True)
    op.create_index(op.f('ix_document_google_parent_id'), 'document', ['google_parent_id'], unique=False)
    op.create_index(op.f('ix_document_mime_type'), 'document', ['mime_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_mime_type'), table_name='document')
    op.drop_index(op.f('ix_document_google_parent_id'), table_name='document')
    op.drop_index(op.f('ix_document_google_id'), table_name='document')
    op.drop_index(op.f('ix_document_filename'), table_name='document')
    op.drop_index(op.f('ix_document_accounting_record'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
