"""add new tables

Revision ID: d46a231df696
Revises: 415d32f993b8
Create Date: 2018-08-26 18:14:48.922463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46a231df696'
down_revision = '415d32f993b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('show_details_in_report', sa.Boolean(), nullable=False),
    sa.Column('show_count_in_report', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_name'), ['name'], unique=False)

    op.create_table('paymenttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('has_members', sa.Boolean(), nullable=False),
    sa.Column('show_details_in_report', sa.Boolean(), nullable=False),
    sa.Column('show_count_in_report', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymenttype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymenttype_name'), ['name'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('payment_type_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['payment_type_id'], ['paymenttype.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_name'), ['name'], unique=False)

    with op.batch_alter_table(u'transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_budget_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposed_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'paymenttype', ['proposed_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'budget', ['proposed_budget_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposed_type_id')
        batch_op.drop_column('proposed_budget_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_name'))

    op.drop_table('payment')
    with op.batch_alter_table('paymenttype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymenttype_name'))

    op.drop_table('paymenttype')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_name'))

    op.drop_table('budget')
    # ### end Alembic commands ###
