"""empty message

Revision ID: e8325b3bbc36
Revises: 9f2d247b886a
Create Date: 2025-03-16 20:15:38.709276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8325b3bbc36'
down_revision = '9f2d247b886a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('description_on_negative', sa.String(length=300), server_default='', nullable=False))
    op.drop_column('budget', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('description', sa.VARCHAR(length=300), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('budget', 'description_on_negative')
    # ### end Alembic commands ###
