"""empty message

Revision ID: f46a8f149209
Revises: 6fe9dcaf0816
Create Date: 2025-07-10 20:06:00.209357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46a8f149209'
down_revision = '6fe9dcaf0816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innertransfer',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('fk_innertransfer_budget_id_budget')),
    sa.ForeignKeyConstraint(['from_id'], ['innerbudget.id'], name=op.f('fk_innertransfer_from_id_innerbudget')),
    sa.ForeignKeyConstraint(['to_id'], ['innerbudget.id'], name=op.f('fk_innertransfer_to_id_innerbudget')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_innertransfer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('innertransfer')
    # ### end Alembic commands ###
